### ISSUE TITLE
Shopify Integration: Creating a Simple Shopify App

### ISSUE THREAD

**Issue by ricardobrg** [tiki/examples#41]
Create a simple Shopify app that loads the TIKI SDK JS.

On the initialization, it should create a custom user id for the user and save it in the [user meta fields](https://shopify.dev/docs/apps/custom-data/metafields#developer-resources) if it is logged in or in a cookie when the user is not logged in. When the user registers, it saves the user id in the user meta fields.

The [sample app](https://shopify.dev/docs/apps/getting-started/create) from the getting started tutorial will be used as starting point.

**Comment by ricardobrg** [comment]
### Tasks
- [ ] integrate Tiki Sdk
- [ ] prompt user on page load
- [ ] save TIKI user id in the user meta fields / cookies
- [ ] save TIKI user id to the user meta fields when the user is created

**Comment by ricardobrg** [comment]
The [app theme extension](7b82db47aa001b8700a06d0be5b41676db12d736) is the starting point for implementing this. 
The discount coupon creation and the TIKI user id attribution must be better defined in other stories.
